substitutions:
  clack_select_chl_or_dpsw: Functie mode
  clack_distance: Zoutniveau afstand
  clack_distance_tof: Zoutniveau afstand TOF
  clack_procent: Zoutniveau procent
  clack_animation: Zoutniveau voor dashboard
  clack_height: Zoutniveau hoogte
  clack_watermeter_total: Watermeter
  clack_m3_left: Waterontharder m3 over
  clack_l_left: Waterontharder ltr over
  clack_version: Versie
  clack_regeneration_last: Geregenereerd op
  clack_fill_salt: Zout bijvullen
  clack_saltlevel_height_min: Min afstand zout
  clack_saltlevel_height_max: Max afstand zout
  clack_saltlevel_height_fill: Zout bijvullen afstand
  clack_capacity_liters: Capaciteit in liters
  clack_capacity_days: Capaciteit in dagen
  clack_chlorinator_delay: Chlorinator aktief tijd
  clack_watermeter_pulse: Watermeter pulse
  clack_regeneration_pulse: Regeneratie pulse
  clack_ip: Waterontharder IP
  clack_wifi_signal_db: WiFi Signaal dB
  clack_wifi_signal_db_percent: WiFi Signaal
  clack_uptime: Uptime
  clack_chlorinator: Chlorinator
  clack_salt_level_measurement: Zoutniveau meting
  hours: uur
  days: dagen
  clack_yes: ja
  clack_no: nee
  clack_on: Aan
  clack_off: Uit
  clack_power: Vermogen Clack
  clack_voltage: Spanning
  clack_power_esp: Vermogen ESP
  clack_power_chlorinator: Vermogen Chlorinator
  clack_restart: ESP Herstart
  clack_regen: clack regen
  clack_brine: Tijdens bezouten
  clack_regeneration_mode: Regeneratie mode
  clack_time_to_regen: Tijd tot regen.
  clack_time_to_resinclean: Tijd tot harscleaner
  clack_cycle_runtime: Cyclus runtime
  clack_cycle_total_runtime: Cyclus totale runtime
  clack_resinclean_capacity_days: Harsclean dagen
  clack_reset_but_last_dist: Reset zout bijgevuld
  clack_resinclean_last: Harscleaner op
  clack_saltfill_last: Zout bijgevuld op
  clack_cycle_step: Cyclus stap

text_sensor:
  # Expose last regeneration information as sensor
  - platform: template
    name: ${clack_regeneration_last}
    id: clack_regeneration_last
    icon: mdi:clock-start
    update_interval: never
    lambda: |-
      return id(regen_date_last);
    filters:   
      - substitute:
        - "Jan -> jan"
        - "Feb -> feb"
        - "Mar -> mar"
        - "Apr -> apr"
        - "May -> mei"
        - "Jun -> jun"
        - "Jul -> jul"
        - "Aug -> aug"
        - "Sep -> sep"
        - "Okt -> okt"
        - "Nov -> nov"
        - "Dec -> dec"
        - "Mon -> maa"
        - "Tue -> din"
        - "Wed -> woe"
        - "Thu -> don"
        - "Fri -> vri"
        - "Sat -> zat"
        - "Sun -> zon" 

  # Expose last resinclean information as sensor
  - platform: template
    name: ${clack_resinclean_last}
    id: clack_resinclean_last
    icon: mdi:clock-start
    update_interval: never
    lambda: |-
      return id(resinclean_date_last);
    filters:   
      - substitute:
        - "Jan -> jan"
        - "Feb -> feb"
        - "Mar -> mar"
        - "Apr -> apr"
        - "May -> mei"
        - "Jun -> jun"
        - "Jul -> jul"
        - "Aug -> aug"
        - "Sep -> sep"
        - "Okt -> okt"
        - "Nov -> nov"
        - "Dec -> dec"
        - "Mon -> maa"
        - "Tue -> din"
        - "Wed -> woe"
        - "Thu -> don"
        - "Fri -> vri"
        - "Sat -> zat"
        - "Sun -> zon" 

  # Expose last salt fill information as sensor
  - platform: template
    name: ${clack_saltfill_last}
    id: clack_saltfill_last
    icon: mdi:clock-start
    update_interval: never
    lambda: |-
      return id(fill_last);
    filters:   
      - substitute:
        - "Jan -> jan"
        - "Feb -> feb"
        - "Mar -> mar"
        - "Apr -> apr"
        - "May -> mei"
        - "Jun -> jun"
        - "Jul -> jul"
        - "Aug -> aug"
        - "Sep -> sep"
        - "Okt -> okt"
        - "Nov -> nov"
        - "Dec -> dec"
        - "Mon -> maa"
        - "Tue -> din"
        - "Wed -> woe"
        - "Thu -> don"
        - "Fri -> vri"
        - "Sat -> zat"
        - "Sun -> zon" 