#-----------
#UTILITY METER
#-----------
utility_meter:
  clack_waterverbruik_dit_kwartier:  
    source: sensor.clack_watermeter
    cycle: quarter-hourly
  clack_waterverbruik_dit_uur:
    source: sensor.clack_watermeter
    cycle: hourly
  clack_waterverbruik_vandaag:
    source: sensor.clack_watermeter
    cycle: daily 
  clack_waterverbruik_maand:
    source: sensor.clack_watermeter
    cycle: monthly
  clack_waterverbruik_jaar:
    source: sensor.clack_watermeter
    cycle: yearly 

#-----------
#AUTOMATIONS
#-----------
automation:
  #------------------------------------------------------------------
  # Extra optie: Zout niveau alarm
  # Vul je eigen mobile_app_iphone_van_xxx in. (als voorbeeld)            
  #------------------------------------------------------------------
  - id: salt_level_alarm_notify
    alias: Ontharder - Zoutniveau alarm melding
    description: ''
    trigger:
    - platform: state
      entity_id: sensor.clack_zout_bijvullen
      to: ja
    condition:
    - condition: time
      after: 07:30:00
      before: '22:00:00'
    action:
    - action: notify.mobile_app_iphone_van_a_c_a
      data:
        title: Let op!
        message: Zout niveau van ontharder is laag! Vandaag gaan bijvullen!
        data:
          push:
            sound:
              name: default
              critical: 1
              volume: 1
    - delay:
        minutes: 30
    initial_state: 'true'
    mode: single

  #------------------------------------------------------------------------------------
  # Nog een extra optie: Lekkage van water alarm - continu verbruik L/min na xx minuten
  # Vul je eigen mobile_app_iphone_van_xxx in. (als voorbeeld)            
  #------------------------------------------------------------------------------------
  - id: water_leakage_alarm_notify
    alias: Ontharder - Lekkage van water alarm melding
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.clack_lekkage_gedetecteerd
      to: "on"    
    action:
    - action: notify.mobile_app_iphone_van_a_c_a
      data:
        title: Let op!
        message: Lekkage van water gedetecteerd!
        data:
          push:
            sound:
              name: default
              critical: 1
              volume: 1
    initial_state: 'true'
    mode: restart