## Time-of-Flight Distance Unit (VL53L1X) M5stack  SKU: U172
## Remark: I2C grove cable max 2 mtr
## https://shop.m5stack.com/products/time-of-flight-distance-unit-vl53l1x
## tof_vl53l1x.h needed in root directory together with clack.yaml for compiling in esphome

esphome:
  includes:
    - tof_vl53l1x.h  #ToF4M M5stack
  libraries:
    - "Wire"
    - "pololu/VL53L1X"

sensor:
# VL53L1X TOF               
  - platform: custom
    lambda: |-
      auto my_sensor = new MyCustomSensor();
      App.register_component(my_sensor);
      return {my_sensor};

    sensors:
      id: distance_cm
      name: ${clack_distance_tof}
      unit_of_measurement: inch
      accuracy_decimals: 1
      device_class: distance
      state_class: measurement
      icon: mdi:ruler
      internal: false
      filters:
        - lambda: |-
            if (isnan(x)) {
              return 0;
            } else {
              return x;
            }
        - lambda: return x/10;
        - clamp:
            min_value: 0.0
            max_value: 230.0
#        - median:
        - delta: 0.2
        - lambda: return (x* 0.39370079); # cm to inch
      on_value:
        then:
          - sensor.template.publish:
              id: clack_distance
              state: !lambda |-
                return id(distance_cm).state;