substitutions:
  device_description: "Clack test for Atom s3 lite"
  timezone: "Europe/Amsterdam"

esphome:
  name: clack-test
  friendly_name: Clack Test
  name_add_mac_suffix: false


esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: clack-test
    password: "configesp"
    ap_timeout: 15s

captive_portal:

# Sync time with sntp server
time:
  - platform: sntp
    id: sntp_time
    timezone: ${timezone}

# Enable logging
logger:
  baud_rate: 0
  logs:
    esp32.preferences: DEBUG
    sensor: DEBUG
    text_sensor: DEBUG
    switch: DEBUG
    button: DEBUG
    number: DEBUG
    component: ERROR


# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:
  - platform: esphome
  
web_server:
  port: 80


sensor:
# Diagnostics wifi and uptime      
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    id: clack_wifi_signal_db
    name: clack_wifi_signal_db
    update_interval: 60s
    entity_category: diagnostic
    internal: True

  - platform: uptime
    id: clack_uptime
    name: clack_uptime
    unit_of_measurement: days
    update_interval: 3600s
    accuracy_decimals: 1
    filters:
      - multiply: 0.000011574

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    id: clack_version
    name: clack_version
    hide_timestamp: true
    icon: mdi:new-box
    entity_category: diagnostic

  # Expose WiFi information as sensor.
  - platform: wifi_info
    ip_address:
      name: Clack IP
      icon: mdi:ip-network
  
light:
#G35=RGB WS2812C-2020
  - platform: esp32_rmt_led_strip
    name: Led
    id: led
    rgb_order: GRB
    pin: 35
    num_leds: 4
#    brightness: 0.7
    # RMT 0 channels will be occupied by IR
    rmt_channel: 1
    chipset: ws2812
#    restore_mode: ALWAYS_ON
    internal: True

#G41=Button
binary_sensor:
  - platform: gpio
    id: esp_button
    pin:
      number: GPIO41
      inverted: true
      mode:
        input: true
        pullup: true
    internal: false
    filters:
      - delayed_off: 10ms


## ESP restart button
button:
  - platform: restart
    id: restart_button
    name: ESP restart
